using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Blog.ProjectEuler
{
    public class Problem2
    {
        //Even Fibonacci numbers
        //Each new term in the Fibonacci sequence is generated by adding the previous two terms.By starting with 1 and 2, the first 10 terms will be:

        //                                    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

        //By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

        /*Notes:
            I first attempted to use an Array then decided that a List was better. Once I understood the problem, my approach was correct but
            I didn't have the parenthesis correct in my if statement. UGH! It caused a lot of pain!
        */
        public static long Answer()
        {
            var fibonacciNumbers = new List<long>();
            fibonacciNumbers.Add(1);
            fibonacciNumbers.Add(1);

            var numberOfElements = fibonacciNumbers.Count();

            var x = fibonacciNumbers.ElementAt(numberOfElements - 2);
            var y = fibonacciNumbers.ElementAt(numberOfElements - 1);
            long result = 0;
            long sum = 0;

            while (result < 4000000)
            {
                if ((result % 2) == 0)
                {
                    sum += result;
                }
                result = x + y;
                y = x;
                x = result;
            }

            return sum;

        }

    }
}
