<%@ Page Title="" Language="C#" MasterPageFile="~/SingleBlogPost.Master" AutoEventWireup="true" CodeBehind="Problem2Blog.aspx.cs" Inherits="Blog.Web.WebForm8" %>
<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <section class="global-page-header">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <div class="block">
                            <h2>Project Euler: Problem 2</h2><br />
                            <h3>Even Fibonacci numbers</h3>
                            <div class="portfolio-meta">
                                <span>July 30, 2016</span>|
                                <span>Completion Time: Untimed</span>|
                                <span> Link: <a href="https://projecteuler.net/problem=2">Project Euler P.2</a>    <%--,<a href="">people</a></span>--%></span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            </section><!--/#Page header-->
            <section class="single-post">
                <div class="container">
                    <div class="row">
                        <div class="col-md-12">
                            
                            <div class="post-content">
                                <blockquote>
                                    Problem 2: Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
                                    <p>1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...</p>
                                    <p>
                                        By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
                                    </p>
                                </blockquote>
                                    <p>
                                       Like <a href="Problem1Blog.aspx">Problem 1</a>, I immediately had a plan in my head after reading this problem. 
                                        However, it did take a little longer to solve than the first one. 
                                    </p>
                                <p>
                                    My first thought was to first add all of the fibonacci numbers into an array with a for iteration and then use the Array.Sum() method. 
                                    I soon figured out that it wasn't the best approach. I ultimately decided to use a List<> and while statement and quickly 
                                    came up with a solution. 
                                </p>
                                <p>
                                    I've really been enjoying being challenged with the problems.
                                </p>
                                <p>
                                    Below I've attached a photo of my solution. If you have any suggestions on how I can improve it or want to share your
                                    own solution with me, vist my <a href="Contact.aspx">Contact Me</a> page.    
                                </p>
                                <br />
                                <p>
                                    Also, don't forget to visit the <a href="ProjectEulerDemos.aspx">Live Demo</a>.
                                </p>
                                <br />
                                <p>Whitney</p>
                                <%--<ol>
                                    <li>Ipsum dolor sit amet.</li>
                                    <li>Lorem sit amet.</li>
                                    <li>Lorem ipsum dolor sit amet.</li>
                                    <li>Lorem ipsum dolor amet.</li>
                                </ol>--%>
                            </div>
                                <figure class="wow fadeInLeft animated" data-wow-duration="500ms" data-wow-delay="300ms">
                                <div class="img-wrapper">
                                    <img src="images/blogpic2.png" class="img-responsive" alt="" >
                                    <div class="overlay">
                                        <div class="buttons">
                                            <a rel="gallery" class="fancybox" href="images/NewFolder1/blogpic1.png">Enlarge</a>
                                        </div>
                                    </div>
                                </div>
                                <figcaption>
                                <h4>
                                <a href="images/NewFolder1/blogpic1.png">
                                    Even Fibonacci numbers
                                </a>
                                </h4>
                                </figcaption>
                            </figure>
                            </div>
                        </div>
                    </div>
            </section>
</asp:Content>
